{% set name = "mlsauce" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Techtonique/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 253aa489236fbe6a69f50ac793da154104b17040ddf90bd1cefeae334c7e285a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:  
    - cython >=0.29.21  
    - numpy
    - pip
    - python =3.10
    - requests
    - setuptools
    - scipy   
  run:
    - numpy
    - python 3.10
    - cython >=0.29.21  
    - scipy >=1.7.0
    - scikit-learn >=1.0.0
    - matplotlib-base
    - pandas >=1.3.5
    - joblib >=0.14.0
    - requests
    - six >=1.16.0
    - threadpoolctl >=2.0.0
    - tqdm >=4.48.1
    - seaborn
    - jax >=0.4
    - jaxlib >=0.4
    - nnetsauce

test:
  requires:
    - pip
    - numpy
    - scipy
    - scikit-learn
  imports:
    - mlsauce
  commands:
    - python -c "import mlsauce; print('ok')"
    
about:
  home: https://techtonique.github.io/mlsauce/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Miscellaneous Statistical/Machine learning stuff
  description: Miscellaneous Statistical/Machine learning stuff.
  doc_url: https://techtonique.github.io/mlsauce/
  dev_url: https://github.com/Techtonique/mlsauce

extra:
  recipe-maintainers:
    - thierrymoudiki
