{% set name = "mlsauce" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Techtonique/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6a3e1fba68fd50dc9a942754c2aad27b0ea335af6dc74e6aac57b37febd53062

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:  
    - cython >=0.29.21  
    - numpy
    - pip
    - python    
    - setuptools
    - scipy    
  run:
    - python
    - scipy >=0.19.0
    - scikit-learn >=0.18.0
    - matplotlib-base
    - pandas >=1.3.5
    - jax     # [unix]
    - jaxlib      # [unix]
    - joblib >=0.14.0
    - six >=1.16.0
    - threadpoolctl >=2.0.0
    - tqdm >=4.48.1
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pip
  commands:
    - pip check
  imports: 
    - mlsauce

about:
  home: https://techtonique.github.io/mlsauce/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Miscellaneous Statistical/Machine learning stuff
  description: Miscellaneous Statistical/Machine learning stuff.
  doc_url: https://techtonique.github.io/mlsauce/
  dev_url: https://github.com/Techtonique/mlsauce

extra:
  recipe-maintainers:
    - thierrymoudiki
